#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define PB push_back
#define SH std::cout <<
#define LN << '\n'
#define RD std::cin >>
#define va std::vector<auto>

#define dd long double

using namespace std;
typedef std::vector<int> vi;
template <typename _A, typename _B> using umap = unordered_map<_A, _B>;
template <typename T> using v = vector<T>;

template <typename T> void RD_VC(v<T> &a, int n) {}

auto solve(dd a, dd b, dd c) {
  dd result = pow(a, b);
  dd lsb = round(fmod(result, pow(10.0, c)));
  dd t = 1;
  // and not equal
  while (result > t - 0.1) {
    t *= 10.0;
  }
  // 10^x-c
  t /= pow(10., c);
  int msb = floor(result / t);
  cout << msb << " ";
  if (lsb == 0) {
    REP(_, c) { cout << "0"; }
  } else {
    cout << lsb;
  }
  cout << endl;
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  dd a, b, c;
  cin >> a >> b >> c;
  solve(a, b, c);
  return 0;
}
