#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


def solve(x1, y1, x2, y2, x3, y3):
    # try moving x2
    for i in range(1, 9):
        # we can't jump over other rook

        if is_mate(x1, y1, i, y2, x3, y3):
            return YES


def is_mate(x1, y1, x2, y2, x3, y3):
    return x1 == 0 or x1 == 9 or y1 == 0 or y1 == 9 or x1 == x2 or y1 == y2 or x1 == x3 or y1 == y3

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    for i in range(a):
        b[i], c[i] = map(int, input().split())
        for j in range(c_i):
            d[i][j], e[i][j] = map(int, input().split())
    f = solve(a, b, c, d, e)
    for i in range(a):
        print(f[i])


if __name__ == '__main__':
    main()
