# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = 100
    print(testcases)
    for _ in range(testcases):
        n = random.randint(1, 100)
        print(n)
        for _ in range(n):
            print(random.randint(-100, 100), end=" ")
        print()

if __name__ == "__main__":
    main()
