#include <bits/stdc++.h>
#include <climits>
#include <stack>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define PB push_back
#define SH std::cout <<
#define LN << '\n'
#define RD std::cin >>
#define va std::vector<auto>

using namespace std;
typedef std::vector<int> vi;
template <typename _A, typename _B> using umap = unordered_map<_A, _B>;
template <typename T> using v = vector<T>;

template <typename T> void RD_VC(v<T> &a, int n) {}

bool keep[1000000];
auto solve(const string &a) {
  int i = 0;
  char cl = CHAR_MAX;
  stack<int> goods;
  int cli = INT_MAX;
  for (int i = 0; i < a.size(); i++) {
    if (a[i] <= cl) {
      // put this on good list
      while (!goods.empty() && a[goods.top()] > a[i]) {
        int idx = goods.top();
        keep[idx] = false;

        if (idx < cli) {
          cli = idx;
          cl = a[idx];
        }
        goods.pop();
      }
      goods.push(i);
      keep[i] = true;
    } else {
      keep[i] = false;
      if (cl == CHAR_MAX) {
        cl = a[i];
      }
    }
  }
  for (int i = 0; i < a.size(); i++) {
    if (keep[i]) {
      cout << a[i];
    }
  }
  for (int i = 0; i < a.size(); i++) {
    if (!keep[i]) {
      cout << a[i];
    }
  }
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int n;
  std::cin >> n;
  std::vector<std::string> a(n);
  REP(i, n) {
    std::cin >> a[i];
    solve(a[i]);
    cout << endl;
  }
  std::cout << '\n';
  return 0;
}
