#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: List[int], c: List[int], d: List[int], e: List[int]) -> Tuple[str, List[str]]:
def solve(a, b, c, d, e):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    d = [None for _ in range(a)]
    e = [None for _ in range(a)]
    for i in range(a):
        b[i], c[i], d[i], e[i] = map(int, input().split())
    g, m = solve(a, b, c, d, e)
    print(g)
    print(*[m[i] for i in range(a)])


if __name__ == '__main__':
    main()
