Traceback (most recent call last):
  File "/home/manmeet/.local/lib/python3.10/site-packages/onlinejudge_template/generator/hook.py", line 28, in _execute_hook
    return subprocess.check_output(data['hook'], input=rendered, stderr=sys.stderr)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yapf', '--style', '{BASED_ON_STYLE: google, COLUMN_LIMIT: 9999}']' returned non-zero exit status 1.


Generated code (before processed by the filter):
#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = random.randint(1, 10)  # TODO: edit here
    a = [None for _ in range(testcases)]
    b = [None for _ in range(testcases)]
    c = [[None for _ in range(a_i)] for _ in range(testcases)]
    d = [[[None for _ in range(j_i)] for _ in range(a_i)] for _ in range(testcases)]
    for i in range(testcases):
        a[i] = random.randint(1, 10)  # TODO: edit here
        b[i] = random.randint(1, 10)  # TODO: edit here
        for j in range(a_i):
            c[i][j] = random.randint(1, 10)  # TODO: edit here
            for k in range(j_i):
                d[i][j][k] = random.randint(1, 10)  # TODO: edit here
    print(testcases)
    for i in range(testcases):
        print()
        print(a[i], b[i])
        for j in range(a_i):
            print(c[i][j], *[d[i][j][k] for k in range(j_i)])

if __name__ == "__main__":
    main()
