#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = random.randint(1, 1000)  # TODO: edit here
    a = [None for _ in range(testcases)]
    b = [[None for _ in range(a_i)] for _ in range(testcases)]
    for i in range(testcases):
        a[i] = random.randint(1, 10**9)  # TODO: edit here
        for j in range(a_i):
            b[i][j] = random.randint(1, 10**9)  # TODO: edit here
    print(testcases)
    for i in range(testcases):
        print(a[i])
        print(*[b[i][j] for j in range(a_i)])


if __name__ == "__main__":
    main()
