#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    print(1)
    for _ in range(1):
        n = random.randint(1, 5)
        print(n)
        for _ in range(n):
            a = random.randint(1, 10)
            b = a + random.randint(0, 10)
            print(a, b, random.randint(1, 10), sep=' ')

if __name__ == "__main__":
    main()
