#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define PB push_back
#define SH std::cout <<
#define LN << '\n'
#define RD std::cin >>
#define va std::vector<auto>

using namespace std;
typedef std::vector<int> vi;
template <typename _A, typename _B> using umap = unordered_map<_A, _B>;
template <typename T> using v = vector<T>;

template <typename T> void RD_VC(v<T> &a, int n) {}

int solve(int n, int k, vi &a) {
  sort(a.begin(), a.end());
  REP(i, k) {
    int x = n - k - i - 1;
    int y = n - 1 - i;
    a[x] /= a[y];
  }
  int score = 0;
  for (int i = 0; i < n - k; i++) {
    score += a[i];
  }
  return score;
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int testcases;
  std::cin >> testcases;
  while (testcases--) {
    int n, k;
    std::cin >> n >> k;
    vi a(n);
    REP(i, n) { std::cin >> a[i]; }
    std::cout << solve(n, k, a) LN;
  }
  return 0;
}
