#!/usr/bin/env python3
# from typing import *


# def solve(testcases: int, a: List[int]) -> Any:
def solve(testcases, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = int(input())
    a = [None for _ in range(testcases)]
    for i in range(testcases):
        a[i] = int(input())
    ans = solve(testcases, a)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
