#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define PB push_back
#define SH std::cout <<
#define LN << '\n'
#define RD std::cin >>
#define va std::vector<auto>

using namespace std;
typedef std::vector<int> vi;
template <typename _A, typename _B>
using umap = unordered_map<_A, _B>;
template <typename T>
using v = vector<T>;

template <typename T>
void RD_VC(v<T> &a, int n) {}

void solve() {
    int q;
    vi a;
    umap<int, pair<int, int>> m;
    RD(q);

    REP (_, q) {
        int t, x, y;
        RD(t);
        if (t == 1) {
            cin >> x;
            a.PB(x);
        }
        if (t == 2) {
            cin >> x >> y;
            m[x] = {y, a.size() - 1};
        }
    }

    REP (i, a.size()) {
        if (m.find(a[i]) != m.end()) {
            int value = m[a[i]].first;
            if (i < m[a[i]].second) {
                a[i] = value;
            }
        }

        cout << a[i] << ' ';
    }

    cout << endl;
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    solve();
    return 0;
}
