#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(n: int, a: List[int]) -> Tuple[str, str, str, str, List[str], str, List[str]]:
def solve(n, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n = int(input())  # TODO: edit here
    a = list(map(int, input().split()))  # TODO: edit here
    a, b, c, d, e, f, g = solve(n, a)
    print(a)
    print(b, c, d)
    for i in range(d):
        print(e[i])
    print(f, *[g[i] for i in range(f)])


if __name__ == '__main__':
    main()
