#!/usr/bin/env pypy3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    t = 1000;
    print(t);
    for _ in range(t):
        n = random.randint(1, 100000)
        print(n)

if __name__ == "__main__":
    main()
