#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: int) -> Tuple[List[str], List[List[str]], List[List[str]]]:
def solve(a, b, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c = map(int, input().split())
    d, f, m = solve(a, b, c)
    for i in range(c):
        print(d[i], end=' ')
        for j in range(d_i):
            print(f[i][j], end=' ')
            print(m[i][j], end=' ')
        print()


if __name__ == '__main__':
    main()
