#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(a: str, b: int) -> Any:
def solve(a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = int(input())
    ans = solve(a, b)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
