# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def do_it():
    n = random.randint(1, 10)
    m = random.randint(1, 10)
    print(n, m, sep=' ')
    for i in range(n):
        print(random.randint(1, 1000000000), end=' ')
    print()

    for i in range(m):
        print(random.randint(1, 1000000000), end=' ')

if __name__ == "__main__":
    print(1)
    for _ in range(1):
        do_it()
        print()
