#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int) -> Tuple[int, int]:
def solve(a, b, c, d, e, f, g, h):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = int(input())
    c, d, e = map(int, input().split())
    f = int(input())
    g, h = map(int, input().split())
    m, n = solve(a, b, c, d, e, f, g, h)
    print(m)
    print(n)


if __name__ == '__main__':
    main()
