#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define PB push_back
#define SH std::cout <<
#define LN << '\n'
#define RD std::cin >>
#define va std::vector<auto>

using namespace std;
typedef std::vector<int> vi;
template <typename _A, typename _B> using umap = unordered_map<_A, _B>;
template <typename T> using v = vector<T>;

template <typename T> void RD_VC(v<T> &a, int n) {}

void solve(int64_t a, int64_t b) {
  int i = 0;
  int j = b;
  v<pair<int, int>> v;
  while (j >= 0 && i <= a) {
    if (i == 0 && j == 0) {
      j--;
      i++;
      continue;
    }
    v.PB({i, j});
    j--;
    i++;
  }
  cout << v.size() LN;
  for (auto &p : v) {
    cout << p.first << " " << p.second LN;
  }
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t a, b;
  std::cin >> a >> b;
  solve(a, b);
  return 0;
}
